title: Welcome to My Twisted Mind
author: Chloe Ratte
email: nope@secret.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  webbed sight

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
